target-version = "py312"

[lint]
select = ["ALL"]
ignore = [
  "ARG002",
  "BLE001",
  "C901",
  "COM812",
  "CPY001",
  "D101",
  "D102",
  "D103",
  "D104",
  "D107",
  "D203",
  "D212",
  "D401",
  "E501",
  "PLR0912",
  "PLR0915",
  "PLR2004",
  "S101",
]

[lint.isort]
combine-as-imports = true
required-imports = ["from __future__ import annotations"]

[lint.per-file-ignores]
"**/tests/**/*.py" = ["SLF001"]
"examples/**/*.py" = ["INP001"]
